"""
LangGraph Multi-Agent Video Analysis Pipeline

Architecture:
[START] → [supervisor_1] → Fan-out(simple_workers) → [simple_reducer] → [supervisor_2] → Fan-out(complex_workers) → [output_formatter] → [END]

Uses Send API for dynamic fan-out/fan-in parallelism.
Supervisor only receives pred fields, not full reasoning.
"""

import asyncio
import datetime
import logging
import shutil
from pathlib import Path
from typing import Annotated, Any, TypedDict
import operator

from langgraph.types import Send
from langgraph.graph import END, StateGraph

from nodes import (
    complex_worker_node,
    output_formatter_node,
    root_agent_node,
    simple_reducer_node,
    simple_worker_node,
    supervisor_1_node,
    supervisor_2_node,
)

logger = logging.getLogger(__name__)


def build_video_url_from_config(config: dict, video_path: str) -> str:
    prefix = str(config.get("paths", {}).get("video_url_prefix", "file:///app/videos")).rstrip("/")
    return f"{prefix}/{video_path}"


class AgentState(TypedDict):
    """State schema for the LangGraph pipeline."""

    # Video info
    video_path: str
    video_url: str
    video_info: dict  # {"duration": float, "fps": int}
    output_dir: str

    # Shared context
    config: dict
    qwen_client: Any  # QwenClient instance
    skills_dir: str

    # Previous preds from external context (e.g., previous video's results)
    previous_preds: dict

    # Stage 1: Simple tasks
    simple_tasks: list[dict]  # Generated by supervisor_1
    simple_preds: Annotated[list[dict], operator.add]  # Output from simple workers (Send API accumulates here)
    simple_traces: Annotated[list[dict], operator.add]  # Trace from simple workers
    agent_outputs: Annotated[list[dict], operator.add]

    # Stage 2: Complex tasks
    merged_simple: dict  # Reducer output
    complex_tasks: list[dict]  # Generated by supervisor_2
    complex_direct_results: dict
    complex_preds: Annotated[list[dict], operator.add]  # Output from complex workers (Send API accumulates here)
    complex_traces: Annotated[list[dict], operator.add]  # Trace from complex workers
    expected_complex_slices: int

    # Final output
    final_output: dict


def _cleanup_tool_clips(video_root: str, video_path: str, config: dict | None = None) -> None:
    """Delete temporary clip files generated during pipeline execution."""
    paths_cfg = (config or {}).get("paths", {})
    configured_root = paths_cfg.get("tool_clip_root")
    if not configured_root:
        configured_root = Path(paths_cfg.get("output_base", "/app/outputs/scene_mining")) / "_tool_clips"
    candidate_roots = [Path(configured_root), Path(video_root) / "_tool_clips"]
    video_stem = Path(video_path).stem
    date_str = datetime.date.today().strftime("%Y%m%d")
    for clips_root in candidate_roots:
        video_clip_dir = clips_root / date_str / video_stem
        if not video_clip_dir.exists():
            continue
        try:
            shutil.rmtree(video_clip_dir)
            logger.info("Cleaned up tool clips: %s", video_clip_dir)
        except Exception as e:
            logger.warning("Failed to clean up tool clips %s: %s", video_clip_dir, e)


def get_video_info(video_path: str) -> dict:
    """Get video duration and fps using ffprobe."""
    import subprocess
    import json

    try:
        result = subprocess.run(
            [
                "ffprobe", "-v", "error",
                "-select_streams", "v:0",
                "-show_entries", "stream=duration,r_frame_rate",
                "-of", "json",
                video_path
            ],
            capture_output=True,
            text=True,
            timeout=30,
        )
        data = json.loads(result.stdout or "{}")
        streams = data.get("streams", [{}])
        stream = streams[0] if streams else {}

        duration = float(stream.get("duration", 0) or 0)
        fps_str = stream.get("r_frame_rate", "30/1")
        if "/" in fps_str:
            num, den = fps_str.split("/")
            fps = int(float(num) / float(den)) if float(den) != 0 else 30
        else:
            fps = int(fps_str)

        return {"duration": duration, "fps": fps}
    except Exception as e:
        logger.warning("Failed to get video info for %s: %s", video_path, e)
        return {"duration": 0, "fps": 1}


# =============================================================================
# Conditional Edge Functions (Fan-out)
# =============================================================================

def fan_out_simple_workers(state: AgentState) -> list[Send]:
    """
    Conditional edge: supervisor_1 → simple_workers (parallel fan-out).

    Returns a list of Send objects, one per simple task.
    """
    simple_tasks = state.get("simple_tasks", [])
    if not simple_tasks:
        logger.warning("No simple tasks to fan-out")
        return []

    sends = []
    for task in simple_tasks:
        send = Send(
            "simple_worker",
            {
                "task": task,
                "video_path": state["video_path"],
                "video_url": state["video_url"],
                "video_info": state["video_info"],
                "output_dir": state["output_dir"],
                "qwen_client": state["qwen_client"],
                "config": state["config"],
                "skills_dir": state["skills_dir"],
                "on_step": state.get("on_step"),
            },
        )
        sends.append(send)

    logger.info("Fan-out to %d simple workers", len(sends))
    return sends


def _build_output_formatter_bypass(state: AgentState) -> list[Send]:
    """Build a Send directly to output_formatter, bypassing complex workers."""
    return [
        Send(
            "output_formatter",
            {
                "merged_simple": state.get("merged_simple", {}),
                "complex_preds": state.get("complex_preds", []),
                "complex_direct_results": state.get("complex_direct_results", {}),
                "simple_traces": state.get("simple_traces", []),
                "complex_traces": state.get("complex_traces", []),
                "agent_outputs": state.get("agent_outputs", []),
                "output_dir": state.get("output_dir", ""),
                "complex_tasks": state.get("complex_tasks", []),
            },
        )
    ]


def fan_out_complex_workers(state: AgentState) -> list[Send]:
    """
    Conditional edge: supervisor_2 → complex_workers (parallel fan-out).

    Returns a list of Send objects, one per complex task.
    """
    complex_tasks = state.get("complex_tasks", [])
    if not complex_tasks:
        logger.info("No complex tasks to fan-out, route directly to output_formatter")
        return _build_output_formatter_bypass(state)

    sends = []
    for task in complex_tasks:
        slices = task.get("time_slices")
        if not isinstance(slices, list) or not slices:
            maybe_single = task.get("time_slice")
            slices = [maybe_single] if isinstance(maybe_single, dict) else []
        if not slices:
            continue
        for idx, one_slice in enumerate(slices):
            if not isinstance(one_slice, dict):
                continue
            sub_agent_id = f"{task.get('category', 'unknown')}_slice_{idx + 1}"
            send = Send(
                "complex_worker",
                {
                    "task": task,
                    "time_slice": one_slice,
                    "slice_idx": idx,
                    "sub_agent_id": sub_agent_id,
                    "video_path": state["video_path"],
                    "video_url": state["video_url"],
                    "video_info": state["video_info"],
                    "output_dir": state["output_dir"],
                    "qwen_client": state["qwen_client"],
                    "config": state["config"],
                    "skills_dir": state["skills_dir"],
                    "merged_simple": state.get("merged_simple", {}),
                    "on_step": state.get("on_step"),
                },
            )
            sends.append(send)

    if not sends:
        logger.info("Complex tasks exist but no valid slices, route directly to output_formatter")
        return _build_output_formatter_bypass(state)
    logger.info("Fan-out to %d complex workers", len(sends))
    return sends


# =============================================================================
# Graph Construction
# =============================================================================

def build_video_analysis_graph() -> StateGraph:
    """Build the LangGraph StateGraph for video analysis."""

    workflow = StateGraph(AgentState)

    # Add nodes
    workflow.add_node("supervisor_1", supervisor_1_node)
    workflow.add_node("simple_reducer", simple_reducer_node)
    workflow.add_node("supervisor_2", supervisor_2_node)
    workflow.add_node("simple_worker", simple_worker_node)  # Used via Send API
    workflow.add_node("complex_worker", complex_worker_node)  # Used via Send API
    workflow.add_node("output_formatter", output_formatter_node)

    # Set entry point
    workflow.set_entry_point("supervisor_1")

    # Edge: supervisor_1 → simple_workers (conditional fan-out via Send API)
    workflow.add_conditional_edges(
        "supervisor_1",
        fan_out_simple_workers,
    )

    # Edge: simple_workers → simple_reducer (fan-in)
    workflow.add_edge("simple_worker", "simple_reducer")

    # Edge: simple_reducer → supervisor_2
    workflow.add_edge("simple_reducer", "supervisor_2")

    # Edge: supervisor_2 → complex_workers (conditional fan-out via Send API)
    workflow.add_conditional_edges(
        "supervisor_2",
        fan_out_complex_workers,
    )

    # Edge: complex_workers → output_formatter (direct fan-in; complex_reducer removed)
    workflow.add_edge("complex_worker", "output_formatter")

    # Edge: output_formatter → END
    workflow.add_edge("output_formatter", END)

    return workflow


_compiled_graph = None
_compiled_react_graph = None


def _get_compiled_graph():
    """Return the compiled DAG graph, building it once on first call."""
    global _compiled_graph
    if _compiled_graph is None:
        _compiled_graph = build_video_analysis_graph().compile()
        logger.info("LangGraph pipeline compiled (once per process)")
    return _compiled_graph


def _get_compiled_react_graph():
    """Return the compiled ReAct graph, building it once on first call."""
    global _compiled_react_graph
    if _compiled_react_graph is None:
        _compiled_react_graph = build_react_video_analysis_graph().compile()
        logger.info("ReAct LangGraph pipeline compiled (once per process)")
    return _compiled_react_graph


# =============================================================================
# Pipeline Execution
# =============================================================================

async def run_video_analysis(
    video_path: str,
    video_root: str,
    output_dir: str,
    qwen_client,
    config: dict,
    skills_dir: str,
    previous_preds: dict | None = None,
    on_step=None,
) -> dict:
    """
    Run the LangGraph pipeline for a single video.

    Args:
        video_path: Relative path within video_root
        video_root: Root directory for videos
        output_dir: Output directory for this video's results
        qwen_client: Initialized QwenClient
        config: Full config dict
        skills_dir: Path to skills directory
        previous_preds: Optional dict of predictions from prior context

    Returns:
        final_output: dict with all category results
    """
    # Build full video path
    full_video_path = str(Path(video_root) / video_path)
    video_url = build_video_url_from_config(config, video_path)

    # Get video info
    video_info = get_video_info(full_video_path)

    # Ensure output dir exists
    video_output_dir = Path(output_dir) / Path(video_path).stem
    video_output_dir.mkdir(parents=True, exist_ok=True)

    # Initial state
    initial_state: AgentState = {
        "video_path": video_path,
        "video_url": video_url,
        "video_info": video_info,
        "output_dir": str(video_output_dir),
        "config": config,
        "qwen_client": qwen_client,
        "skills_dir": skills_dir,
        "on_step": on_step,
        "previous_preds": previous_preds or {},
        "simple_tasks": [],
        "simple_preds": [],
        "simple_traces": [],
        "agent_outputs": [],
        "merged_simple": {},
        "complex_tasks": [],
        "complex_direct_results": {},
        "complex_preds": [],
        "complex_traces": [],
        "expected_complex_slices": 0,
        "final_output": {},
    }

    # Build and compile graph (reuses module-level compiled graph)
    compiled = _get_compiled_graph()

    # Run
    if on_step:
        on_step("vlm", "VLM分析中...", {"phase": "simple"})
    logger.info("Starting LangGraph pipeline for video: %s", video_path)
    result = await compiled.ainvoke(initial_state)

    # result is the final state
    final_output = result.get("final_output", {})

    logger.info("LangGraph pipeline completed for %s: %d categories",
                video_path, len(final_output))

    # Clean up temporary clip files generated during this video's pipeline run
    _cleanup_tool_clips(video_root, video_path, config)

    return final_output


async def run_video_analysis_streaming(
    video_path: str,
    video_root: str,
    output_dir: str,
    qwen_client,
    config: dict,
    skills_dir: str,
    previous_preds: dict | None = None,
):
    """
    Streaming version of run_video_analysis.

    Yields intermediate states for progress tracking.
    """
    full_video_path = str(Path(video_root) / video_path)
    video_url = build_video_url_from_config(config, video_path)
    video_info = get_video_info(full_video_path)

    video_output_dir = Path(output_dir) / Path(video_path).stem
    video_output_dir.mkdir(parents=True, exist_ok=True)

    initial_state: AgentState = {
        "video_path": video_path,
        "video_url": video_url,
        "video_info": video_info,
        "output_dir": str(video_output_dir),
        "config": config,
        "qwen_client": qwen_client,
        "skills_dir": skills_dir,
        "previous_preds": previous_preds or {},
        "simple_tasks": [],
        "simple_preds": [],
        "simple_traces": [],
        "agent_outputs": [],
        "merged_simple": {},
        "complex_tasks": [],
        "complex_direct_results": {},
        "complex_preds": [],
        "complex_traces": [],
        "expected_complex_slices": 0,
        "final_output": {},
    }

    compiled = _get_compiled_graph()

    try:
        async for state in compiled.astream(initial_state):
            yield state
    finally:
        _cleanup_tool_clips(video_root, video_path, config)


# =============================================================================
# ReAct Agent Pipeline
# =============================================================================

class ReActAgentState(TypedDict):
    """State schema for the ReAct agent pipeline."""

    # Video info
    video_path: str
    video_url: str
    video_info: dict
    output_dir: str

    # Shared context
    config: dict
    qwen_client: Any
    skills_dir: str
    previous_preds: dict

    # ReAct agent output
    category_results: dict          # category -> {pred, events, ...}
    on_step: Any                    # Optional callback for interactive output

    # Legacy compatibility (for output_formatter)
    merged_simple: dict
    simple_preds: Annotated[list[dict], operator.add]
    simple_traces: Annotated[list[dict], operator.add]
    agent_outputs: Annotated[list[dict], operator.add]
    complex_preds: Annotated[list[dict], operator.add]
    complex_traces: Annotated[list[dict], operator.add]
    complex_direct_results: dict
    expected_complex_slices: int
    # Final output
    final_output: dict


def build_react_video_analysis_graph() -> StateGraph:
    """Build the ReAct-based LangGraph StateGraph.

    Simple topology: root_agent → output_formatter → END

    The root_agent internally handles all coordination via
    spawn_sub_agent, query_result, and review_result tools.
    """
    workflow = StateGraph(ReActAgentState)

    workflow.add_node("root_agent", root_agent_node)
    workflow.add_node("output_formatter", output_formatter_node)

    workflow.set_entry_point("root_agent")
    workflow.add_edge("root_agent", "output_formatter")
    workflow.add_edge("output_formatter", END)

    return workflow


async def run_react_video_analysis(
    video_path: str,
    video_root: str,
    output_dir: str,
    qwen_client,
    config: dict,
    skills_dir: str,
    previous_preds: dict | None = None,
    on_step=None,
) -> dict:
    """
    Run the ReAct agent pipeline for a single video.

    Args:
        video_path: Relative path within video_root
        video_root: Root directory for videos
        output_dir: Output directory for this video's results
        qwen_client: Initialized QwenClient
        config: Full config dict
        skills_dir: Path to skills directory
        previous_preds: Optional dict of predictions from prior context
        on_step: Optional callback(step_type, data) for interactive output

    Returns:
        final_output: dict with all category results
    """
    full_video_path = str(Path(video_root) / video_path)
    video_url = build_video_url_from_config(config, video_path)
    video_info = get_video_info(full_video_path)

    video_output_dir = Path(output_dir) / Path(video_path).stem
    video_output_dir.mkdir(parents=True, exist_ok=True)

    initial_state: dict = {
        "video_path": video_path,
        "video_url": video_url,
        "video_info": video_info,
        "output_dir": str(video_output_dir),
        "config": config,
        "qwen_client": qwen_client,
        "skills_dir": skills_dir,
        "previous_preds": previous_preds or {},
        "category_results": {},
        "on_step": on_step,
        # Legacy compatibility defaults
        "merged_simple": {},
        "simple_preds": [],
        "simple_traces": [],
        "agent_outputs": [],
        "complex_preds": [],
        "complex_traces": [],
        "expected_complex_slices": 0,
        "complex_direct_results": {},
        "final_output": {},
    }

    compiled = _get_compiled_react_graph()

    logger.info("Starting ReAct agent pipeline for video: %s", video_path)
    result = await compiled.ainvoke(initial_state)

    final_output = result.get("final_output", {})
    logger.info("ReAct agent pipeline completed for %s: %d categories",
                video_path, len(final_output))

    _cleanup_tool_clips(video_root, video_path, config)

    return final_output
